import random

list_of_ls = ["literature",
"loneliness",
"legendary",
"laceration",
"leukemia",
"locomotive",
"longevity",
"liberation",
"loveliness",
"liaison",
"liveliness",
"linebacker",
"locomotion",
"levitation",
"lifestlye",
"librarian",
"legislation",
"locality",
"lifesaver",
"limitation",
"listeria",
"lacrimation",
"litigation",
"liquidation",
"leviticus",
"lieutenant",
"luxuria",
"louisville",
"leviathan",
"lollygagging",
"legislature",
"lobotomy",
"lederhosen",
"lugubrious",
"lutetium",
"lineation",
"livelihood",
"lobbying",
"liberia",
"legislating",
"ladyfinger",
"lovesickness",
"lifelessly",
"literacy",
"lamentation",
"lothario",
"lavatory",
"luxurious",
"liquefaction",
"licentious"
]


def find_random_l():
    last_int = len(list_of_ls)
    index = random.randint(0,last_int)
    return list_of_ls[index]